

--
-- Criação do usuário
CREATE USER CALCULADORA IDENTIFIED BY CALCULADORA;

GRANT CREATE SESSION TO CALCULADORA;
GRANT DBA TO CALCULADORA;




--
-- Funções do Sistema

CREATE OR REPLACE FUNCTION SOMA(a NUMBER, b NUMBER) RETURN NUMBER AS
  result NUMBER;
BEGIN
  result := a + b;
  RETURN result;
END SOMA;
/



CREATE OR REPLACE FUNCTION SUBTRACAO(a NUMBER, b NUMBER) RETURN NUMBER AS
  result NUMBER;
BEGIN
  result := a - b;
  RETURN result;
END SUBTRACAO;
/



CREATE OR REPLACE FUNCTION MULTIPLICACAO(a NUMBER, b NUMBER) RETURN NUMBER AS
  result NUMBER;
BEGIN
  result := a * b;
  RETURN result;
END MULTIPLICACAO;
/



CREATE OR REPLACE FUNCTION DIVISAO(a NUMBER, b NUMBER) RETURN NUMBER AS
  result NUMBER;
BEGIN
  IF b = 0 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Divisão por zero não é permitida.');
  END IF;
  result := a / b;
  RETURN result;
END DIVISAO;
/




