--
-- Gerenciador - WDS_PLSQL_TDD


	
--
---- Criação dos usuários do Gerenciador	

-- Usuário Principal que realiza o gerenciamento. Fica a seu critério a definição de senha e tablespace.
CREATE USER WDS_PLSQL_TDD IDENTIFIED BY WDS_PLSQL_TDD;


GRANT CREATE SESSION TO WDS_PLSQL_TDD;
GRANT UNLIMITED TABLESPACE TO WDS_PLSQL_TDD;
GRANT DBA TO WDS_PLSQL_TDD;
GRANT CREATE ANY PROCEDURE TO WDS_PLSQL_TDD;
GRANT EXECUTE ANY PROCEDURE TO WDS_PLSQL_TDD;
GRANT SELECT ANY TABLE TO WDS_PLSQL_TDD;
GRANT SELECT ON SYS.DBA_USERS TO WDS_PLSQL_TDD;
GRANT SELECT ON SYS.DBA_OBJECTS TO WDS_PLSQL_TDD;
GRANT SELECT ON SYS.DBA_ARGUMENTS TO WDS_PLSQL_TDD;
GRANT SELECT ON SYS.GV_$SESSION TO WDS_PLSQL_TDD;
GRANT SELECT ON SYS.GV_$PROCESS TO WDS_PLSQL_TDD;
GRANT EXECUTE ON DBMS_SYSTEM TO WDS_PLSQL_TDD;
GRANT EXECUTE ON DBMS_SESSION TO WDS_PLSQL_TDD;
GRANT EXECUTE ON DBMS_PIPE TO WDS_PLSQL_TDD;
GRANT ALTER SESSION TO WDS_PLSQL_TDD;
GRANT ALTER SYSTEM TO WDS_PLSQL_TDD;
GRANT CREATE JOB TO WDS_PLSQL_TDD;
GRANT EXECUTE ON DBMS_SCHEDULER TO WDS_PLSQL_TDD;
GRANT MANAGE SCHEDULER TO WDS_PLSQL_TDD; 
GRANT SELECT ON SYS.DBA_DEPENDENCIES TO WDS_PLSQL_TDD;
GRANT ALTER ANY PROCEDURE TO WDS_PLSQL_TDD;




-- Usuário responsável por armazenar os Testes que serão criados. Fica a seu critério a definição de senha e tablespace.
CREATE USER WDS_PLSQL_TDD_TESTE IDENTIFIED BY WDS_PLSQL_TDD_TESTE;

GRANT CREATE SESSION TO WDS_PLSQL_TDD_TESTE;
GRANT DBA TO WDS_PLSQL_TDD_TESTE;
GRANT EXECUTE ANY PROCEDURE TO WDS_PLSQL_TDD_TESTE;
GRANT SELECT ANY TABLE TO WDS_PLSQL_TDD_TESTE;
GRANT DELETE ANY TABLE TO WDS_PLSQL_TDD_TESTE;
GRANT CREATE PROCEDURE TO WDS_PLSQL_TDD_TESTE;
GRANT INSERT ANY TABLE TO WDS_PLSQL_TDD_TESTE;



--
-- Conectar com o Usuário WDS_PLSQL_TDD


-- Criar diretórios. Realizar essa ação após configurar o a instalação do Shell Script de Coleta do Trace

CREATE DIRECTORY WDS_PLSQL_TDD_SCRIPT AS '/u01/aplic/wds_tdd_script';

CREATE DIRECTORY WDS_PLSQL_TDD_TRACE  AS '/u01/aplic/wds_tdd_script/trace';







