


DROP TABLE WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA;

CREATE TABLE WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA (
	VALOR_A NUMBER NOT NULL,
	VALOR_B NUMBER NOT NULL
);




--
-- Função de teste
CREATE OR REPLACE FUNCTION GERAR_VALORES_TESTE_CALCULADORA RETURN BOOLEAN IS
/*
{NOME:Gera valores para teste Calculadora}
{INFO:Cria os valores que aleatórios que serão usados nos calculos matemáticos dos testes }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:CALCULAR}
*/

	v_NUM_A NUMBER;

	v_NUM_B NUMBER;

	v_RESULTADO NUMBER;
	
BEGIN


	FOR i IN 1..10 LOOP

		v_NUM_A := TRUNC( DBMS_RANDOM.VALUE(1, 100) );

		v_NUM_B := TRUNC( DBMS_RANDOM.VALUE(1, 100) );
		
		INSERT INTO WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA ( VALOR_A, VALOR_B ) VALUES ( v_NUM_A, v_NUM_B );

	END LOOP;


	v_RESULTADO := SQL%ROWCOUNT;
	

	COMMIT;


	RETURN ( v_RESULTADO > 0 );


END;
/








--
-- Função de teste
CREATE OR REPLACE FUNCTION LIMPAR_VALORES_TESTE_CALCULADORA RETURN BOOLEAN IS
/*
{NOME:Deleta valores do teste da calculadora}
{INFO:Apaga os valores que foram gerados para os testes matemáticos a serem realizados }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:SOMA}
{TESTE_AUXILIAR}
*/
	v_RESULTADO NUMBER;
	
BEGIN

	DELETE FROM WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA;
	
	v_RESULTADO := SQL%ROWCOUNT;
	
	COMMIT;
	
	RETURN ( v_RESULTADO > 0 );

END;
/








--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_SOMA( p_VALOR_A IN NUMBER, p_VALOR_B IN NUMBER ) RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Soma}
{INFO:Realiza testes matemáticos da operação SOMA }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:SOMA}
{QUERY_ARGUMENTO:SELECT VALOR_A, VALOR_B FROM WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA}
{ANTES:GERAR_VALORES_TESTE_CALCULADORA}
{DEPOIS:LIMPAR_VALORES_TESTE_CALCULADORA}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.SOMA( p_VALOR_A, p_VALOR_B ) = ( p_VALOR_A + p_VALOR_B );
		
END;
/







--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_SUBTRACAO( p_VALOR_A IN NUMBER, p_VALOR_B IN NUMBER ) RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Subtração}
{INFO:Realiza testes matemáticos da operação SUBTRACAO }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:SUBTRACAO}
{QUERY_ARGUMENTO:SELECT VALOR_A, VALOR_B FROM WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA}
{ANTES:GERAR_VALORES_TESTE_CALCULADORA}
{DEPOIS:LIMPAR_VALORES_TESTE_CALCULADORA}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.SUBTRACAO( p_VALOR_A, p_VALOR_B ) = ( p_VALOR_A - p_VALOR_B );
		
END;
/







--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_MULTIPLICACAO( p_VALOR_A IN NUMBER, p_VALOR_B IN NUMBER ) RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Multiplicação}
{INFO:Realiza testes matemáticos da operação MULTIPLICACAO }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:MULTIPLICACAO}
{QUERY_ARGUMENTO:SELECT VALOR_A, VALOR_B FROM WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA}
{ANTES:GERAR_VALORES_TESTE_CALCULADORA}
{DEPOIS:LIMPAR_VALORES_TESTE_CALCULADORA}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.MULTIPLICACAO( p_VALOR_A, p_VALOR_B ) = ( p_VALOR_A * p_VALOR_B );
		
END;
/






--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_DIVISAO( p_VALOR_A IN NUMBER, p_VALOR_B IN NUMBER ) RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Divisão}
{INFO:Realiza testes matemáticos da operação DIVISAO }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:DIVISAO}
{QUERY_ARGUMENTO:SELECT VALOR_A, VALOR_B FROM WDS_PLSQL_TDD_TESTE.TESTES_CALCULADORA}
{ANTES:GERAR_VALORES_TESTE_CALCULADORA}
{DEPOIS:LIMPAR_VALORES_TESTE_CALCULADORA}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.DIVISAO( p_VALOR_A, p_VALOR_B ) = ( p_VALOR_A / p_VALOR_B );
		
END;
/







