


CREATE OR REPLACE PROCEDURE ADICIONAR_PRODUTO( p_NOME VARCHAR2, p_QUANTIDADE NUMBER, p_PRECO VARCHAR2 ) AS
BEGIN

  INSERT INTO ESTOQUE ( NOME, QUANTIDADE, PRECO) VALUES ( p_NOME, p_QUANTIDADE, p_PRECO);


  COMMIT;

END ADICIONAR_PRODUTO;
/









CREATE OR REPLACE PROCEDURE REALIZAR_VENDA( p_PRODUTO_ID NUMBER, p_QUANTIDADE NUMBER ) AS

  v_PRECO BINARY_FLOAT;

  v_VALOR_VENDA BINARY_FLOAT;

BEGIN


  SELECT PRECO INTO v_PRECO FROM ESTOQUE WHERE ID = p_PRODUTO_ID;


  IF p_QUANTIDADE > 0 THEN


    v_VALOR_VENDA := ( v_PRECO * p_QUANTIDADE );
  
    INSERT INTO VENDAS ( PRODUTO_ID, QUANTIDADE_VENDIDA, DATA_VENDA, VALOR_VENDA) VALUES ( p_PRODUTO_ID, p_QUANTIDADE, SYSDATE, v_VALOR_VENDA);
    
    UPDATE ESTOQUE SET QUANTIDADE = ( QUANTIDADE - p_QUANTIDADE ) WHERE ID = p_PRODUTO_ID;

    COMMIT;
  
  ELSE
  
    RAISE_APPLICATION_ERROR(-20001, 'QUANTIDADE DE VENDA INVÁLIDA.');
  
  END IF;

END REALIZAR_VENDA;
/



