


CREATE USER VENDAS_ESTOQUE IDENTIFIED BY VENDAS_ESTOQUE;

GRANT DBA TO VENDAS_ESTOQUE;
GRANT CREATE SESSION TO VENDAS_ESTOQUE;


DROP SEQUENCE SEQ_ESTOQUE;

DROP SEQUENCE SEQ_VENDAS;

DROP TABLE VENDAS;

DROP TABLE ESTOQUE;



CREATE SEQUENCE SEQ_ESTOQUE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_VENDAS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



CREATE TABLE ESTOQUE (
  ID NUMBER DEFAULT SEQ_ESTOQUE.NEXTVAL PRIMARY KEY,
  NOME VARCHAR2(255),
  QUANTIDADE NUMBER,
  PRECO BINARY_FLOAT NOT NULL
);



CREATE TABLE VENDAS (
  ID NUMBER DEFAULT SEQ_VENDAS.NEXTVAL PRIMARY KEY,
  PRODUTO_ID NUMBER,
  QUANTIDADE_VENDIDA NUMBER,
  DATA_VENDA DATE,
  VALOR_VENDA BINARY_FLOAT NOT NULL,
  FOREIGN KEY (PRODUTO_ID) REFERENCES ESTOQUE(ID)
);





