

-- Tabela: TEMPO_EXECUCAO_TESTE
-- Descrição: Armazena o tempo de execução de cada teste realizado



--
-- Sequence para a definição do ID
CREATE SEQUENCE SEQ_TEMPO_EXECUCAO_TESTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



CREATE TABLE TEMPO_EXECUCAO_TESTE
(
  ID NUMBER DEFAULT SEQ_TEMPO_EXECUCAO_TESTE.NEXTVAL NOT NULL 
, FK_TESTE_ID NUMBER NOT NULL
, ID_EXECUCAO NUMBER(16) NOT NULL
, CODIGO NUMBER NOT NULL
, ROWID_ARGUMENTO VARCHAR2(4000) NOT NULL
, TEMPO_EXECUCAO BINARY_FLOAT NOT NULL
, SITUACAO VARCHAR2(20)
, CONSTRAINT TEMPO_EXECUCAO_TESTE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


ALTER TABLE TEMPO_EXECUCAO_TESTE ADD CONSTRAINT TEMPOS_EXEC_TESTES_FK_TESTE_ID FOREIGN KEY ( FK_TESTE_ID ) REFERENCES TESTE ( ID ) ENABLE;

ALTER TABLE TEMPO_EXECUCAO_TESTE ADD CONSTRAINT TEMPO_EXECUCAO_SITUACAO_CHK CHECK ( SITUACAO IN ( 'SUCESSO', 'FALHA', 'RAISE_ERROR' ) ) ENABLE;


COMMENT ON TABLE TEMPO_EXECUCAO_TESTE IS '--

-- Armazena o tempo de execução de cada teste realizado.
--
-- Autor: Wesley David Santos
-- Skype: wesleydavidsantos		
-- https://www.linkedin.com/in/wesleydavidsantos
--';

COMMENT ON COLUMN TEMPO_EXECUCAO_TESTE.ID IS 'Identificador único do TEMPO_EXECUCAO_TESTE';

COMMENT ON COLUMN TEMPO_EXECUCAO_TESTE.FK_TESTE_ID IS 'Identificação do teste';

COMMENT ON COLUMN TEMPO_EXECUCAO_TESTE.ID_EXECUCAO IS 'ID que identifica de forma única todos os TESTE realizados em um único processo de validação';

COMMENT ON COLUMN TEMPO_EXECUCAO_TESTE.CODIGO IS 'Código de identificação do teste, usado como identificação na tabela HISTORICO_EXECUCAO_TESTES';

COMMENT ON COLUMN TEMPO_EXECUCAO_TESTE.ROWID_ARGUMENTO IS 'Identifica a linha com os argumentos que foram testados';

COMMENT ON COLUMN TEMPO_EXECUCAO_TESTE.TEMPO_EXECUCAO IS 'Tempo de execução do teste em milisegundos';

