

-- Tabela: TRACE_METADADOS
-- Descrição: Armazena todos os METADADOS gerados sobre os Testes de TDD que tem a opção de TRACE ativada



--
-- Sequence para a definição do ID
CREATE SEQUENCE SEQ_TRACE_METADADOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



CREATE TABLE TRACE_METADADOS
(
  ID NUMBER DEFAULT SEQ_TRACE_METADADOS.NEXTVAL NOT NULL
, FK_TESTE_ID NUMBER NOT NULL 
, ID_EXECUCAO NUMBER NOT NULL
, DATA_CRIADO DATE DEFAULT SYSDATE NOT NULL 
, DATA_SITUACAO_ALTERADO DATE NOT NULL 
, ARQUIVO VARCHAR2(100) NOT NULL 
, SITUACAO VARCHAR2(50) NOT NULL 
, CONSTRAINT PK_TRACE_METADADOS PRIMARY KEY ( ID ) USING INDEX ( 
                                                        CREATE UNIQUE INDEX TRACE_METADADOS_PK ON TRACE_METADADOS ( ID ASC ) 
                                                     ) ENABLE 
);

ALTER TABLE TRACE_METADADOS ADD CONSTRAINT UK_TRACE_METADADOS_ARQUIVO UNIQUE ( ARQUIVO ) USING INDEX 
(
    CREATE UNIQUE INDEX TRACE_METADADOS_ARQUIVO_UK ON TRACE_METADADOS (ARQUIVO ASC) 
) ENABLE;

ALTER TABLE TRACE_METADADOS ADD CONSTRAINT FK_TRACE_METADADOS_FK_TESTE_ID FOREIGN KEY ( FK_TESTE_ID ) REFERENCES TESTE ( ID ) ENABLE;

ALTER TABLE TRACE_METADADOS ADD CONSTRAINT CHK_TRACE_METADADOS_SITUACAO CHECK ( SITUACAO IN ( 'COLETANDO', 'COLETADO', 'PROCESSANDO', 'FINALIZADO', 'ERRO' ) ) ENABLE;




COMMENT ON TABLE TRACE_METADADOS IS '--

-- Armazena todos os METADADOS gerados sobre os Testes de TDD que tem a opção de TRACE ativada
--
-- Autor: Wesley David Santos
-- Skype: wesleydavidsantos		
-- https://www.linkedin.com/in/wesleydavidsantos
--';


COMMENT ON COLUMN TRACE_METADADOS.ID IS 'Identificador auto-incremento do TRACE_METADADOS';

COMMENT ON COLUMN TRACE_METADADOS.FK_TESTE_ID IS 'Teste em que o TRACE_METADADOS foi coletado';

COMMENT ON COLUMN TRACE_METADADOS.ID_EXECUCAO IS 'ID que identifica de forma única todos os TESTE realizados em um único processo de validação';

COMMENT ON COLUMN TRACE_METADADOS.DATA_CRIADO IS 'Data de criação do TRACE_METADADOS';

COMMENT ON COLUMN TRACE_METADADOS.DATA_SITUACAO_ALTERADO IS 'Data em que a coluna situacao foi alterada';

COMMENT ON COLUMN TRACE_METADADOS.ARQUIVO IS 'Nome do arquivo de TRACE_METADADOS';

COMMENT ON COLUMN TRACE_METADADOS.SITUACAO IS 'Situação atual do TRACE_METADADOS. Opções: COLETANDO - COLETADO - PROCESSANDO - FINALIZADO - ERRO';

