

-- Tabela: HISTORICO_EXECUCAO_TESTES
-- Descrição: Armazena o histórico de execução de testes



--
-- Sequence para a definição do ID das ALVO
CREATE SEQUENCE SEQ_HISTORICO_EXECUCAO_TESTES START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;



CREATE TABLE HISTORICO_EXECUCAO_TESTES
(
  ID NUMBER DEFAULT SEQ_HISTORICO_EXECUCAO_TESTES.NEXTVAL NOT NULL   
, FK_TESTE_ID NUMBER NOT NULL
, ID_EXECUCAO NUMBER(16) NOT NULL
, ORDEM_EXECUCAO NUMBER(16) NOT NULL
, CODIGO NUMBER(16) NOT NULL
, TIPO_TESTE VARCHAR2(6) NOT NULL
, DATA_INICIO DATE NOT NULL
, DATA_FIM DATE DEFAULT SYSDATE NOT NULL
, QTD_TOTAL_TESTE NUMBER NOT NULL
, QTD_TESTE_REALIZADO NUMBER NOT NULL
, QTD_TESTE_SUCESSO NUMBER NOT NULL
, QTD_TESTE_FALHA NUMBER NOT NULL
, QTD_TESTE_RAISE_ERRO NUMBER NOT NULL
, TEMPO_EXECUCAO BINARY_FLOAT NOT NULL
, CONSTRAINT HIST_EXEC_TESTES_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


ALTER TABLE HISTORICO_EXECUCAO_TESTES ADD CONSTRAINT HIST_EXC_TESTE_FK_TESTE_ID FOREIGN KEY ( FK_TESTE_ID ) REFERENCES TESTE ( ID ) ENABLE;

ALTER TABLE HISTORICO_EXECUCAO_TESTES ADD CONSTRAINT HISTORICO_EXEC_TESTES_TIPO_CHK CHECK ( TIPO_TESTE IN ( 'TESTE', 'ANTES', 'DEPOIS' ) ) ENABLE;


COMMENT ON TABLE HISTORICO_EXECUCAO_TESTES IS '--

-- Armazena o histórico de execução de testes
--
-- Autor: Wesley David Santos
-- Skype: wesleydavidsantos		
-- https://www.linkedin.com/in/wesleydavidsantos
--';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.ID IS 'Identificador único do HISTORICO_EXECUCAO_TESTES';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.FK_TESTE_ID IS 'Identificação do teste';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.ID_EXECUCAO IS 'ID que identifica de forma única todos os TESTE realizados em um único processo de validação';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.ORDEM_EXECUCAO IS 'Registra a ordem de execução da sequência de um processo de TESTE';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.CODIGO IS 'Código de identificação do teste, usado como identificação na tabela LOG_FALHA_EXECUCAO_TESTES';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.TIPO_TESTE IS 'Informa qual tipo de teste está sendo realizado. Tipos: TESTE - ANTES - DEPOIS';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.DATA_INICIO IS 'Data de execução do teste';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.QTD_TOTAL_TESTE IS 'Quantidade de testes que devem ser realizados';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.QTD_TESTE_REALIZADO IS 'Quantidade de testes realizados';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.QTD_TESTE_SUCESSO IS 'Quantidade de testes que com sucesso';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.QTD_TESTE_FALHA IS 'Quantidade de testes com falha';

COMMENT ON COLUMN HISTORICO_EXECUCAO_TESTES.QTD_TESTE_RAISE_ERRO IS 'Quantidade de testes com raise error';


