

DROP FUNCTION CALCULADORA_SOMA;

DROP FUNCTION CALCULADORA_SUBTRACAO;

DROP FUNCTION CALCULADORA_MULTIPLICACAO;

DROP FUNCTION CALCULADORA_DIVISAO;




--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_SOMA RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Soma}
{INFO:Realiza testes matemáticos da operação SOMA }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:SOMA}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN
	
	RETURN CALCULADORA.SOMA( 2, 2 ) = 4;
		
END;
/




--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_SUBTRACAO RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Subtração}
{INFO:Realiza testes matemáticos da operação SUBTRAÇÃO }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:SUBTRACAO}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.SUBTRACAO( 2, 2 ) = 0;
		
END;
/



--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_MULTIPLICACAO RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Multiplicação}
{INFO:Realiza testes matemáticos da operação MULTIPLICAÇÃO }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:MULTIPLICACAO}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.MULTIPLICACAO( 2, 2 ) = 4;
		
END;
/



--
-- Função de teste
CREATE OR REPLACE FUNCTION CALCULADORA_DIVISAO RETURN BOOLEAN IS
/*
{NOME:Calculadora Teste Divisão}
{INFO:Realiza testes matemáticos da operação DIVISÃO }
{ALVO_OWNER:CALCULADORA}
{ALVO_OBJECT:DIVISAO}
*/
	
	v_LOG_REGISTRADO NUMBER;

BEGIN

	RETURN CALCULADORA.DIVISAO( 2, 2 ) = 1;
		
END;
/



